export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOT_ISPENDING = 'REQUEST_ROBOT_ISPENDING';
export const REQUEST_ROBOT_SUCCESS = 'REQUEST_ROBOT_SUCCESS';
export const REQUEST_ROBOT_FAILED = 'REQUEST_ROBOT_FAILED';
